In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Slice Notation

In slice notation, the left side of the colon is inclusive while the right side of the colon is exclusive

[*inclusive* : *exclusive*]

In [3]:
arr[1:5]

array([1, 2, 3, 4])

In [4]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [5]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# Broadcasting

In [7]:
arr[0:5] = 100

The value of 100 has been broadcast to elements at index 0, 1, 2, 3, and 4.

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# Copying an Array

In [9]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Creating a slice of an array does not make a copy. It becomes a pointer to that slice of the original array.

In [10]:
slice_of_array = arr[0:6]
slice_of_array

array([0, 1, 2, 3, 4, 5])

Let's set the entire slice to 99.

In [11]:
slice_of_array[:] = 99

In [12]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

When we look again at the original, we see that it has been changed. 

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

***

If we are interested in copying an array, we must use the copy() method.

In [14]:
arr_copy = arr.copy()
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# Matrices

In [16]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Element Selection from a Matrix

Grab first row of matrix

In [17]:
arr_2d[0]

array([ 5, 10, 15])

Grab element "35" using double bracket format

In [18]:
arr_2d[2][0]

35

Grab element "35" using single bracket format

In [19]:
arr_2d[2,0]

35

***

In [20]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

If we want a chunk of the matrix, say 

`` array([[10, 15],
        [25, 30])``

we can use slice notation.

``arr_2d[:2,1:]`` 

grabs all rows up to row 2, and all columns past column 1.

Remember the left side of the colon is inclusive, the right side of the colon is exclusive.

In [21]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Conditional Selection

In [24]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create an array of boolean values by making some comparison.

In [27]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Pass in the boolean array to the original array.

The resulting array is one where the values of the array are true under the comparison that generated the boolean array.

In [28]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

Typically, this is done all in one step:

In [29]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [30]:
arr[arr<3]

array([1, 2])

***

# Exercises

In [33]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Practice grabbing submatricies from this array using Slice Notation

In [36]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [37]:
arr_2d[3:5,0:2]

array([[30, 31],
       [40, 41]])